use std::env;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    let out_dir = format!("{}/protos", std::env::var("OUT_DIR").unwrap());
    std::fs::create_dir_all(&out_dir).unwrap();

    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir(out_dir)
        .inputs(["protos/rendezvous.proto", "protos/message.proto"])
        .include("protos")
        .customize(protobuf_codegen::Customize::default().tokio_bytes(true))
        .run()
        .expect("Codegen failed.");

    // Generate custom config from environment variables
    generate_custom_config();
}

fn generate_custom_config() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("custom_config.rs");
    let mut file = File::create(&dest_path).unwrap();

    // Helper: get env var or default, treating empty string as unset
    fn get_env_or_default(key: &str, default: &str) -> String {
        env::var(key)
            .map(|v| if v.is_empty() { default.to_string() } else { v })
            .unwrap_or_else(|_| default.to_string())
    }

    // Get values from environment variables (set in GitHub Actions)
    // Empty strings are treated as unset, using defaults from official RustDesk
    let rendezvous_server = get_env_or_default("CUSTOM_RENDEZVOUS_SERVER", "rs-ny.rustdesk.com");
    let rs_pub_key = get_env_or_default("CUSTOM_RS_PUB_KEY", "OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=");
    let rendezvous_port = get_env_or_default("CUSTOM_RENDEZVOUS_PORT", "21116");
    let relay_port = get_env_or_default("CUSTOM_RELAY_PORT", "21117");
    let ws_rendezvous_port = get_env_or_default("CUSTOM_WS_RENDEZVOUS_PORT", "21118");
    let ws_relay_port = get_env_or_default("CUSTOM_WS_RELAY_PORT", "21119");

    let content = format!(
        r#"// Auto-generated by build.rs from environment variables
// DO NOT EDIT - This file is generated during build

pub const RENDEZVOUS_SERVERS: &[&str] = &["{}"];
pub const RS_PUB_KEY: &str = "{}";
pub const RENDEZVOUS_PORT: i32 = {};
pub const RELAY_PORT: i32 = {};
pub const WS_RENDEZVOUS_PORT: i32 = {};
pub const WS_RELAY_PORT: i32 = {};
"#,
        rendezvous_server,
        rs_pub_key,
        rendezvous_port,
        relay_port,
        ws_rendezvous_port,
        ws_relay_port
    );

    file.write_all(content.as_bytes()).unwrap();
    println!("cargo:rerun-if-env-changed=CUSTOM_RENDEZVOUS_SERVER");
    println!("cargo:rerun-if-env-changed=CUSTOM_RS_PUB_KEY");
    println!("cargo:rerun-if-env-changed=CUSTOM_RENDEZVOUS_PORT");
    println!("cargo:rerun-if-env-changed=CUSTOM_RELAY_PORT");
    println!("cargo:rerun-if-env-changed=CUSTOM_WS_RENDEZVOUS_PORT");
    println!("cargo:rerun-if-env-changed=CUSTOM_WS_RELAY_PORT");
}
